### ISSUE TITLE
Make Wrath be confirmed as innocent instead of wrath.

### ISSUE THREAD

**Issue by Lunethia** [LunexSan/ttt2-role_wra#1]
Add a convar or something to make the wrath be seen as a plain innocent when confirmed.

**Comment by tobi-nb** [comment]
Yeah that's necessary. For now people stay aside the wrath corpse waiting for his respawn.

**Comment by tobi-nb** [comment]
Or add a random spawn for the wrath

**Comment by Lunethia** [comment]
Oh, I never considered that. A random spawn could be an alternative if I don't get it to work.

But I am still somewhat confident that I'll get it eventually.

The guys on TTT2 have done it with the spy. So it's everything but impossible.

(sadly the spy code is undocumented... so it's taking me a long while..)

**Comment by Lunethia** [comment]
This is now done, and will be pushed to git and the workshop asap. :)
