### ISSUE TITLE
Wrath public role bug

### ISSUE THREAD

**Issue by AaronMcKenney** [LunexSan/ttt2-role_wra#11]
**Version of code:** Commit 732bbd3
**Version of TTT2:** v0.7.3b

**Description:**
Confirming a dead wrath before they respawn appears to reveal their traitor role. This is eerily similar to the [Jester public role bug](https://github.com/TTT-2/ttt2-role_jes/issues/47) issue that has been recently fixed.

**To Reproduce:**
1. Create 2 bots.
2. Force yourself to be innocent, one bot to be a traitor, and one bot to be a wrath.
3. Kill the wrath bot and inspect their body. They will appear as innocent in the confirmation message, but their scoreboard will show them as a wrath (See #9).
4. When they respawn, their role will visibly be that of a traitor (reflected both in the scoreboard and by hovering your crosshair over them).

I believe the fix could be the [same as mentioned in the Jester public role bug](https://github.com/TTT-2/ttt2-role_jes/pull/51/files), which is to add "p:ResetConfirmPlayer()" before "SendFullStateUpdate()" in the Wrath's revive function.

**Comment by Lunethia** [comment]
interesting, that must've been a new bug?`I'll have a look at your commit.

**Comment by Lunethia** [comment]
Since you made the commit which i just merged everything **shouuuullddd** be good now? if not please reopen.
