### ISSUE TITLE
wrath sucide

### ISSUE THREAD

**Issue by Eevori** [LunexSan/ttt2-role_wra#7]
when i know that i am the wrath i can easily kill myself with fire grenades or what ever and i will respawn as a traitor

**Comment by Lunethia** [comment]
I think this was fixed some time ago. But usually you should be unable to know you are a wrath :<

**Comment by Lunethia** [comment]
Can you confirm this still happens?

**Comment by Eevori** [comment]
wrath sucide ist fixed thank you
