### ISSUE TITLE
Wraith color in leaderboard

### ISSUE THREAD

**Issue by guillermomolla** [LunexSan/ttt2-role_wra#9]
I found and issue that probably mess the idea of the wrath.
When you inspect the boddy you can see in the leaderboard that he was the wrath also when it is going to respawn because it was killed by an innocent.
Could it be possible that if it does not show until the end of the game? Like the Spy.
Because if you kill him and you see its body you just need to wait there to kill him again.
Also I think it could be a nice feature that instead of appearing in the body, he just spawns in other site or when he is killed by an innocent, enter in a "invisible state" with a counter telling him when he will respawn as a traitor. This way he can control what he whas arround and spawn in a normal site and not in the middle of everyone.

Thank you so much :D

**Comment by Lunethia** [comment]
Oof. I'll see about this.

**Comment by guillermomolla** [comment]
Also I was investing about how this is programed (as I studied computer science) and do you know if there is any way to don't see the "revived" arrow? As it would be quite obvius there was a wrath.
Obviously this are just ideas, this is your rol and your creation, the only "bug" was the leaderboard one.

But I wanted to just leave some cool ideas if you liked them

**Comment by Lunethia** [comment]
The Leaderboard part is apparently some kind of bug/change. It used to show the innocents colour with the current code. I'll ahve to ask the TTT2 devs on this, but they are busy right now. 

As for the second question, it is intended to show the revived arrow. Since everyone getting revived has it. And normally it should be very obvious someone got revived. The thing that has to be fixed around is everything before the revival.

**Comment by guillermomolla** [comment]
Uhhh okay I understand, also it seems quite funny to try to guess who is revived or does the leaderboard show who has been revived deleting him from the "Confirmed dead" state part of the leaderboard?

**Comment by AaronMcKenney** [comment]
I think you can fix this issue by following the same logic that the Spy uses in their "TTT2ConfirmPlayer" hook:
https://github.com/TTT-2/ttt2-role_spy/blob/master/lua/terrortown/entities/roles/spy/shared.lua

**Comment by Lunethia** [comment]
> Uhhh okay I understand, also it seems quite funny to try to guess who is revived or does the leaderboard show who has been revived deleting him from the "Confirmed dead" state part of the leaderboard?

That is the case yes, usually a revived player should always show as living again, if that mechanic hasn't recently been tinkered with, that is.

**Comment by Lunethia** [comment]
According to mr. mckenney this should be fixed now? I thinks? If not please reopen.
